name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/ServiceUtilities/ServiceUtilities.sln
    - name: Build
      run: dotnet build ./src/ServiceUtilities/ServiceUtilities.sln --no-restore
    - name: Test
      run: dotnet test ./src/ServiceUtilities/ServiceUtilitiesTests/ServiceUtilitiesTests.csproj --no-build --verbosity normal