name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/ServiceUtilities/ServiceUtilities.sln
    - name: Build
      run: dotnet build ./src/ServiceUtilities/ServiceUtilities.sln  -c Release --no-restore
    - name: Test
      run: dotnet test ./src/ServiceUtilities/ServiceUtilitiesTests/ServiceUtilitiesTests.csproj  -c Release --no-build --verbosity normal
    - name: Push
      run: dotnet nuget push ./src/ServiceUtilities/ServiceUtilities/bin/Release/*.nupkg --api-key ${{secrets.PACKAGE_SERVER_TOKEN}} --source https://api.nuget.org/v3/index.json